### ISSUE TITLE
Request for help - Several arrayslist to table

### ISSUE THREAD

**Issue by Buchx** [fmcarvalho/HtmlFlow#29]
My goal is to produce a table with the layout kinda like this:
![double table](https://user-images.githubusercontent.com/31307350/37511865-a434cd50-2900-11e8-85b7-caab76e14d32.png)

The code used for producing this output is: 
```
public static void saveWeek(String weekNum, ArrayList<SkemaLektion> man, ArrayList<SkemaLektion> tir) {
        HtmlView<Iterable<SkemaLektion>> taskView = new HtmlView<Iterable<SkemaLektion>>();
        taskView
                .head()
                .title(weekNum)
        HtmlTable<Iterable<SkemaLektion>> table = taskView
                .body().classAttr()
                .heading(1, weekNum)
                .div()
                .table().classAttr(table);


        HtmlTr<Iterable<SkemaLektion>> headerRow = table.tr();
        headerRow.th().addAttr("rowspan", "9999").text("MANDAG");
        headerRow.th().text("Tid");
        headerRow.th().text("Enhed");
        headerRow.th().text("Fag");
        headerRow.th().text("Lek Nr");
        headerRow.th().text("Aktivitet");
        headerRow.th().text("Leder");
        headerRow.th().text("Påklædning");
        headerRow.th().text("Sted");
        table.trFromIterable(
                skemaLektion -> skemaLektion.getLektid().getText(),
                skemaLektion -> skemaLektion.getEnhed().getSelectionModel().getSelectedItem(),
                skemaLektion -> skemaLektion.getFag().getSelectionModel().getSelectedItem().toString(),
                skemaLektion -> skemaLektion.getLekNummer().getSelectionModel().getSelectedItem().toString(),
                skemaLektion -> skemaLektion.getAktivitet().getText(),
                skemaLektion -> skemaLektion.getAnsvar().getText(),
                skemaLektion -> skemaLektion.getPaaklaedning().getText(),
                (SkemaLektion skemaLektion2) -> skemaLektion2.getLokation().getText());
        
        try (PrintStream out = new PrintStream(new FileOutputStream(weekNum + ".html"))) {
            taskView.setPrintStream(out).write(man);
            taskView.setPrintStream(out).write(tir);
            Desktop.getDesktop().browse(URI.create(weekNum + ".html"));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

My question is how do so that only the table content is added again and not the whole document and the second "Mandag" is changed to "Tirsdag"? (Monday and tuesday.

Kind regards

**Comment by fmcarvalho** [comment]
Hi @Buchx ,

There is no direct support for this Issue in HtmlFlow. But maybe you can work around it with: 

1. Merge the arraylists  in a single List with: `man.addAll(tir)` or `Iterable<SkemaLektion > res = () -> Stream.concat(man.stream(), tir.stream()).iterator();`. Then pass the resulting iterable to the view `taskView.setPrintStream(out).write(res);`

2. Instead of printing the week day in a `th`, just print “Wee Day” on the `th` and then print "Mandag", "Tirsdag", etc in `td` bellow. In that case maybe the type `SkemaLektion` should have a property `getWeekDay()` which provides the data to that `td`: "Mandag", "Tirsdag", etc. Thus you can control inside the lambda if you have already printed the Week Day or not, like: 

```java
WeekDay last = {“”}; 
…
skemaLektion -> {
   if(last[0].equals(skemaLektion.getWeekDay())) return “&nbsp;”
   last[0] = skemaLektion.getWeekDay();
   return skemaLektion.getWeekDay().getText();
}
````

Hope this helps.

**Comment by Buchx** [comment]
Hi, @fmcarvalho 

It now works flawlessly! 
![image](https://user-images.githubusercontent.com/31307350/37521509-557c6c24-2921-11e8-9ddc-d00190df0575.png)

Maybe a bit out of context, but do you know If I can merge thoose cells with the dates OR give it attributes so I can style it a bit more? Or should I just target it with CSS children?

Kind regards

**Comment by fmcarvalho** [comment]
In current version of HtmlFlow `td` s are automatically created by `trFromIterable()` method and there is no way to  specify further attributes on those `td`.s 

On next version 2.0 of HtmlFlow which is in development branch and is being prepared for release **this method `trFromIterable()` is removed** and you have a completely different approach which you can check at the unit test [TestTable.java](https://github.com/fmcarvalho/HtmlFlow/blob/development/src/test/java/htmlflow/test/TestTable.java#L147) and it is like: 

```java
    table.<List<Task>>binder((tbl, list) -> {
            list.forEach(item -> {
                tbl.tr()
                        .td().text(item.getTitle()).º()
                        .td().text(item.getDescription()).º()
                        .td().text(item.getPriority().toString());
            });
        });
```

In this way you can do whatever you want with each `td`.

See the README.md of development branch for further details.

**Comment by Buchx** [comment]
Brilliant! Looking forward to version 2.0!
Thank you for all the help!

**Comment by Buchx** [comment]
When will version 2.0 be released? Really eager to style my tds :)
So I can get it more looking like this: 
![layout](https://user-images.githubusercontent.com/31307350/37545333-d52ce0ba-2968-11e8-9f6e-67085d7ad714.JPG)

Here is what I've made it to currently.
![current](https://user-images.githubusercontent.com/31307350/37545396-f514125e-2968-11e8-9c3b-869cc12b3e2e.png)

Source for above output.
```
public static void saveWeek(
            String weekNum,
            String header,
            String footer,
            String extrasFooter,
            ArrayList<SkemaLektion> lektures) {

        footer = footer.replaceAll("[\n]", "<br />");
        header = header.replaceAll("[\n]", "<br />");
        extrasFooter = extrasFooter.replaceAll("[\n]", "<br />");

        HtmlView<Iterable<SkemaLektion>> taskView = new HtmlView<Iterable<SkemaLektion>>();


        taskView
                .head()
                .title(weekNum)
                .linkCss("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css")
                .scriptBlock()
                .code("</script>\n<meta charset='UTF-8'>\n<script>");

        HtmlBody<Iterable<SkemaLektion>> body = taskView
                .body()
                .classAttr("container");

        // Set header text
        body
                .div()
                .text(header);

        HtmlTable<Iterable<SkemaLektion>> table = body
                .heading(2, "Øvelsesliste for uge " + weekNum.replaceAll("[-]", " "))
                .table().classAttr("table");

        // Set footer text
        body
                .br()
                .div()
                .text(footer);

        if (!extrasFooter.isEmpty()) {
            body
                    .br()
                    .div()
                    .text(extrasFooter);
        }

        String[] last = {""};
        HtmlTr<Iterable<SkemaLektion>> headerRow = table.tr();
        headerRow.th().text("Uge " + weekNum.replaceAll("[-]", " ") + " - " + SkemaController.dp.getValue().getYear());
        headerRow.th().text("Tid");
        headerRow.th().text("Enhed");
        headerRow.th().text("Fag");
        headerRow.th().text("Lek Nr");
        headerRow.th().text("Aktivitet");
        headerRow.th().text("Leder");
        headerRow.th().text("Påklædning");
        headerRow.th().text("Sted");
        table.trFromIterable(
                skemaLektion -> {
                    if (last[0].equals(skemaLektion.getWeekDay())) return "&nbsp;";
                    last[0] = skemaLektion.getWeekDay();
                    return "<div id='" + skemaLektion.getWeekDay().replaceAll("[\n]]","").substring(0, skemaLektion.getWeekDay().length() - 8) + "' style='white-space: pre-wrap;'>" + skemaLektion.getWeekDay() + "</div>";
                },
                skemaLektion -> skemaLektion.getLektid().getText(),
                skemaLektion -> skemaLektion.getEnhedValue(),
                skemaLektion -> skemaLektion.getFagValue(),
                skemaLektion -> skemaLektion.getLekNummerValue(),
                skemaLektion -> skemaLektion.getAktivitet().getText(),
                skemaLektion -> skemaLektion.getAnsvar().getText(),
                skemaLektion -> skemaLektion.getPaaklaedning().getText(),
                (SkemaLektion skemaLektion2) -> skemaLektion2.getLokation().getText());


        String fileName = "Uge_" + weekNum + "_" + SkemaController.dp.getValue().getYear() + ".html";
        try {
            PrintStream out = new PrintStream(new FileOutputStream(fileName), true, "UTF-8");
            taskView.setPrintStream(out).write(lektures);

            Desktop.getDesktop().browse(URI.create(fileName));

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

```
Maybe if you have time you could help me setting up the code for reaching an output similar to picture1?

**Comment by fmcarvalho** [comment]
@Buchx 

> When will version 2.0 be released? Really eager to style my tds :)

Maybe at the end of this week... In meanwhile you can  clone this repository, `checkout development` branch , open a console and run `mvn clean install` and then add a reference to `htmlflow-2.0-SNAPSHOT` in your project.

I can help you with any issue that you find. But I am overwhelmed and I have no time to translate your source code to current version 2.0 HtmlFlow. Try yourself and open an Issue if you have any doubt.

Thanks,
Miguel

**Comment by fmcarvalho** [comment]
@Buchx 

Just to let you know that version 2.0 of HtmlFlow has been released right now.

Now we just have to wait for the synchronization process with Maven Central.

Note that now we are on xmlet oganization: http://repo1.maven.org/maven2/com/github/xmlet/ and 
https://github.com/xmlet/ 

Thanks

**Comment by fmcarvalho** [comment]
@Buchx As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@Buchx Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
