### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marccollin** [fmcarvalho/HtmlFlow#4]
hi

what is the license?

gpl, lgpl, bsd?

thank you

**Comment by fmcarvalho** [comment]
Sorry @marccollin for late response. But this project has been at a standstill. Recently @kenji-getpowered enhanced htmflow with several nice features and resurrected htmlflow. After that I refactored and cleaned some usage examples and deployed it to Maven Central Repository. Now htmlflow is available with coordinates 'com.github.fmcarvalho:htmlflow:1.0'.

And finally and answering your question, we added license GPL 3 to htmlflow.
